<?php if ($this->isEnabled()): ?>
    <script>

        jQuery(document).ready(function() {

            var siteID = getUrlParameter('siteID');
            var n = siteID.length;

            if(n == '34') {
                var date = new Date();
                date.setTime(date.getTime() + (<?php echo Mage::helper('space48_linkshare')->getCookieTime(Mage::app()->getStore()->getStoreId()) ?>));
                jQuery.cookie('affiliatenetwork', 'linkshare', { expires: date, path: '/' });
            }

            function getUrlParameter(sParam)
            {
                var sPageURL = window.location.search.substring(1);
                var sURLVariables = sPageURL.split('&');
                for (var i = 0; i < sURLVariables.length; i++)
                {
                    var sParameterName = sURLVariables[i].split('=');
                    if (sParameterName[0] == sParam)
                    {
                        return sParameterName[1];
                    } else {
                        return false;
                    }
                }
            }
        });
    </script>
<?php endif; ?>